import{a as L,S as v,i as p}from"./assets/vendor-08b0e0f9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function c(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(o){if(o.ep)return;o.ep=!0;const t=c(o);fetch(o.href,t)}})();const d=document.querySelector(".search-form"),n=document.querySelector(".gallery"),f=document.querySelector(".loader-container"),g=document.querySelector(".load-more"),y=L.create({method:"get",baseURL:"https://pixabay.com/api/",params:{key:"41837495-d070c30be5c0243a4bb3b397a",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40}});let s=1;const C=()=>{s++};let l=new v(".gallery a",{captionsData:"alt",captionDelay:250}),m,F;d.addEventListener("submit",async e=>{e.preventDefault(),s=1,q(),n.innerHTML="",l.refresh(),m=d.elements.keywords.value;try{const r=await y({params:{q:m,page:s}});console.log(r.data.total),F=r.data.total,T(),E(r.data)}catch{S()}$(),d.reset()});g.addEventListener("click",async()=>{C();try{const e=await y({params:{q:m,page:s}});M(e.data),h()}catch{b(),h()}});const u=e=>e.hits.map(({largeImageURL:r,webformatURL:c,tags:i,likes:o,views:t,comments:a,downloads:w})=>`
    <li class="img">
       <a href="${r}"><img src="${c}" alt="${i}"></a>
      <ul class="img-info">
        <li class="img-info-item"><span>Likes</span> ${o}</li>
        <li class="img-info-item"><span>Views</span> ${t}</li>
        <li class="img-info-item"><span>Comments</span> ${a}</li>
        <li class="img-info-item"><span>Downloads</span> ${w}</li>
      </ul>
    </li>`).join(""),E=e=>{if(e.hits.length===0)throw new Error(e.status);n.innerHTML=u(e),x(),Math.ceil(e.total/40)<=s&&b(),l.refresh()},M=e=>{if(Math.ceil(e.total/40)<=s)throw n.insertAdjacentHTML("beforeend",u(e)),l.refresh(),new Error(e.status);n.insertAdjacentHTML("beforeend",u(e)),l.refresh()},S=(e="An error occurred.")=>{p.show({message:e,maxWidth:432,iconUrl:"./img/error-icon.svg",iconColor:"#FFFFFF",backgroundColor:"#EF4040",messageColor:"#FFFFFF",position:"topRight"}),n.innerHTML=""},b=()=>{p.show({message:"We're sorry, but you've reached the end of search results.",maxWidth:432,iconUrl:"./img/error-icon.svg",iconColor:"#FFFFFF",backgroundColor:"#87CEEB",messageColor:"#FFFFFF",position:"topRight"}),H()},T=()=>{p.show({message:`We found ${F} images.`,maxWidth:432,backgroundColor:"green",messageColor:"#FFFFFF",position:"topRight"})},h=()=>{const e=document.querySelector(".img").getBoundingClientRect().height*2;window.scrollBy({top:e,behavior:"smooth"})},q=()=>{f.style.display="block"},$=()=>{f.style.display="none"},x=()=>{g.style.display="block"},H=()=>{g.style.display="none"};
//# sourceMappingURL=commonHelpers.js.map
